{{ if not .Values.disableBuiltinRules }}
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: signalfxhttp
  namespace: istio-system
spec:
  match: context.protocol == "http" || context.protocol == "grpc"
  actions:
  - handler: signalfx.istio-system
    instances:
    - requestcount
    - requestduration
    - requestsize
    - responsesize
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: signalfxtcp
  namespace: istio-system
spec:
  match: context.protocol == "tcp"
  actions:
  - handler: signalfx.istio-system
    instances:
    - tcpbytesent
    - tcpbytereceived
{{- end }}
