apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: signalfxtracing
  namespace: istio-system
spec:
  actions:
  - handler: signalfx.istio-system
    instances:
    - signalfxtracespan
  match: {{ .Values.tracespanMatchQuery }}
