apiVersion: v1
kind: Service
metadata:
  name: {{ include "signalfx-istio.fullname" . }}
  namespace: istio-system
  labels:
    app.kubernetes.io/name: {{ include "signalfx-istio.name" . }}
    helm.sh/chart: {{ include "signalfx-istio.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: grpc
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "signalfx-istio.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
