---
# Source: signalfx-adapter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: signalfx-adapter
  namespace: istio-system
  labels:
    app.kubernetes.io/name: signalfx-adapter
spec:
  type: ClusterIP
  ports:
  - name: grpc
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: signalfx-adapter

