name: Go Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  GO_VERSION: "1.14"

jobs:
  go-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Caching dependency
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: go mod download
        run: go mod download

      - name: Install golint
        run: go get -u golang.org/x/lint/golint

  lint:
    runs-on: ubuntu-latest
    needs:
      - go-cache
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Caching dependency
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: lint
        run: golint ./signalfx/... ./cmd/...

  vet:
    runs-on: ubuntu-latest
    needs:
      - go-cache
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Caching dependency
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: vet
        run: CGO_ENABLED=0 go vet ./signalfx/... ./cmd/...

  fmt:
    runs-on: ubuntu-latest
    needs:
      - go-cache
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Caching dependency
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: fmt
        run: |
          go fmt ./signalfx/... ./cmd/...
          git diff --exit-code || (echo 'go files need to be reformatted. Run `go fmt` and commit the changes.' && exit 1)

  tests:
    runs-on: ubuntu-latest
    needs:
      - go-cache
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Caching dependency
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: test
        run: CGO_ENABLED=0 go test -v ./signalfx/...
